Entrega 01
val8558/mentoria-iOS pull request #1
Opened 2024-08-08 12:39 UTC by val8558

2024-08-12 19:00 UTC, yagoal requested changes

2024-08-12 19:00 UTC, yagoal commented on Extensions/Color.swift
> +    static let titleColor = UIColor(_colorLiteralRed: 169/255, green: 147/255, blue: 33/255, alpha: 1.0)
sobrou um espaço aqui na identação

2024-08-12 19:00 UTC, yagoal commented on Extensions/Font.swift
> +}
Boa !!

2024-08-12 19:00 UTC, yagoal commented on mentoria-iOS/Aula 1/CustomView.swift
> +        """
Como a string é bem grande, é melhor utilizar o um arquivo só pra strings ou colocar em outro arquivo e usar aqui.

2024-08-12 19:00 UTC, yagoal commented on mentoria-iOS/Aula 1/CustomView.swift
> +    }
Não precisa colocar isso aqui esse init é só em caso de usar Xib ou StoryBoard

pode retornar só um fatal error aqui pra não precisar fazer setup.

2024-08-12 19:00 UTC, yagoal commented on mentoria-iOS/ViewController.swift
> +}
Nesse caso aqui você não precisa adicionar como subView e setar aos contraist você pode atribuir diretamente no loadView que essa view que você fez

```swift
final class ViewController: UIViewController {
    private lazy var customView = LoginPage()
    
    override func loadView() {
        view = customView
    }
}

```

só isso é o suficiente

2024-08-13 12:42 UTC, yagoal requested changes

2024-08-13 12:42 UTC, yagoal commented on mentoria-iOS/Aula 1/LoginPage.swift
> +//    }()
Isso aqui sobrou ou tu ta rrumando ainda ?

2024-08-13 12:42 UTC, yagoal commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }()
Esse setup aqu ficou grande o ideal é quebrar, pode fazer as bordas e o tile fora e só adicionar como subview, pode tambem tirar as constriant dai pra outra func

2024-08-13 12:42 UTC, yagoal commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }()
mesma coisa o idela é quebrar isso aqui,

2024-08-13 12:42 UTC, yagoal commented on mentoria-iOS/Aula 1/LoginPage.swift
> +//        return buttonStackView
Isso aqui também sobrou ?

2024-08-13 12:42 UTC, yagoal commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }
não precisa fazer setup nessas views aqui não

2024-08-13 12:42 UTC, yagoal commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }
O ideal aqui também é separar por arays cada atributo pra ficar melhor.

2024-08-13 18:47 UTC, val8558 commented on mentoria-iOS/Aula 1/LoginPage.swift
> +//    }()
Isso sobrou, só deixei comentado para ver como faz caso eu precise

2024-08-13 18:48 UTC, val8558 commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }()
Entendi. vou estudar como fazer isso.

2024-08-13 18:49 UTC, val8558 commented on mentoria-iOS/Aula 1/LoginPage.swift
> +//        return buttonStackView
Isso é uma segunda forma de fazer que também deixei guardado para ver como poderia ser feito depois

2024-08-13 18:49 UTC, val8558 commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }
Vou retirar.

2024-08-13 18:50 UTC, val8558 commented on mentoria-iOS/Aula 1/LoginPage.swift
> +    }
Certo. Como poderia fazer isso?

2024-08-23 20:20 UTC, closed without merging